### ISSUE TITLE
Battery 

### ISSUE THREAD

**Issue by gamenhd** [Playlolly/playlolly_tesla_ev#6]
When im driving the battery goes up instead of down

**Comment by Boostvolt** [comment]
Which vehicle do you use?

**Comment by Quinten-Gelderland** [comment]
All of them

**Comment by Boostvolt** [comment]
Have you downloaded tesla_redis, tesla_supercharger and tesla_ev and started them accordingly?

**Comment by Quinten-Gelderland** [comment]
yes i did

**Comment by Boostvolt** [comment]
Please make sure that you do not use scripts on your server that are not compatible with tesla_ev. Try to set up the Tesla scripts on a server without any other scripts to identify the incompatible script. I can then try to fix the error. Because on my server everything works.
