### ISSUE TITLE
tesla_redis dependency error.

### ISSUE THREAD

**Issue by tmtns** [Playlolly/playlolly_tesla_ev#8]
Hello. I have gotten all the three required script but I am getting the following error:

**Could not find dependency tesla_redis for resource playlolly_tesla_ev.**

Any help with that?

**Comment by Boostvolt** [comment]
Thank you for pointing this out. I forgot to update the name. Should work in the latest [1.0.1 release](https://github.com/Playlolly/playlolly_tesla_ev/releases/tag/1.0.1).
